export enum FormTypes  {
  CREATE_NEW_WORK_EXPERIANCE = "CREATE_NEW_WORK_EXPERIANCE",
  DELETE_WORK_EXPERIANCE = "DELETE_WORK_EXPERIANCE",
  UPDATE_WORK_EXPERIANCE = "UPDATE_WORK_EXPERIANCE",
  FETCH_ALL_WORK_EXPERIANCES = "FETCH_ALL_WORK_EXPERIANCES",
  START_LOADING = "START_LOADING",
  END_LOADING = "END_LOADING",
  ERROR = "ERROR",
}